Update zookeeper

diff --git a/zookeeper b/zookeeper
--- a/zookeeper
+++ b/zookeeper
@@ -60,6 +60,26 @@ cp config.cfg target/
 ##run
 nohup java -jar target/zkui-2.0-SNAPSHOT-jar-with-dependencies.jar &
 
+cat >> zkui-run.sh << EOF
+#!/usr/bin/env bash
+home=/opt/zkui
+
+case $1 in
+start)
+nohup java -jar $home/target/zkui-2.0-SNAPSHOT-jar-with-dependencies.jar &
+[ $? -eq 0 ] && echo "OK:Runing.." || echo "Error:Run failed."
+;;
+stop)
+kill -9 `ps -ef | grep zkui | grep -v grep | awk -c '{print $2}'`
+[ $? -eq 0 ] && echo "OK:Stop." || echo "Error:Stop failed."
+;;
+*)
+echo -e "\033[32mUsage: $0 [start|stop]\033[0m"
+exit 1
+;;
+esac
+EOF
+
 ##test
 http://10.10.9.109:9090
 
